### ISSUE TITLE
Add support for anchor tags

### ISSUE THREAD

**Issue by dram55** [speedrunslive/speedrunslive-front-end#46]
react-router does not support anchor tags out of the box. There are many of them in the FAQ pages.

This does not work: `<Link to='#topofpage'>Go To Top</Link>`

Using `<a>` for anchor tags in the meantime.

**Comment by jiano** [comment]
Using a normal anchor tag should be sufficient for linking to same page anchors, yes? It shouldn't be necessary to use react router's link component for this.

**Comment by dram55** [comment]
ye
